# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"shape_list": "00_core.ipynb",
         "maskTF": "00_core.ipynb",
         "SelfAttentionTF": "00_core.ipynb",
         "TransformerBlockTF": "00_core.ipynb",
         "CTransformerTF": "00_core.ipynb"}

modules = ["simple_transformer.py"]

doc_url = "https://jaredwinick.github.io/simple_transformer/"

git_url = "https://github.com/jaredwinick/simple_transformer/tree/master/"

def custom_doc_links(name): return None
